# Generated by Django 2.2.28 on 2024-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('author', models.TextField(max_length=50)),
                ('date', models.TextField(max_length=20)),
            ],
        ),
    ]
